consumes:
- application/json
definitions:
  pbCreateLoginRequest:
    properties:
      userLogin:
        $ref: '#/definitions/pbLogin'
    type: object
  pbCreateLoginResponse:
    properties:
      userLogin:
        $ref: '#/definitions/pbRegister'
    type: object
  pbCreateMovieRequest:
    properties:
      movie:
        $ref: '#/definitions/pbMovie'
    type: object
  pbCreateMovieResponse:
    properties:
      movie:
        $ref: '#/definitions/pbMovie'
    type: object
  pbCreateRegisterRequest:
    properties:
      userRegister:
        $ref: '#/definitions/pbRegister'
    type: object
  pbCreateRegisterResponse:
    properties:
      userRegister:
        $ref: '#/definitions/pbRegister'
    type: object
  pbDeleteMovieResponse:
    properties:
      success:
        type: boolean
    type: object
  pbDeleteUserResponse:
    properties:
      success:
        type: boolean
    type: object
  pbGetMovieResponse:
    properties:
      movie:
        $ref: '#/definitions/pbMovie'
    type: object
  pbGetMoviesResponse:
    properties:
      movies:
        items:
          $ref: '#/definitions/pbMovie'
        type: array
    type: object
  pbGetOneUser:
    properties:
      userId:
        type: string
    type: object
  pbGetOneUserResponse:
    properties:
      userRegister:
        $ref: '#/definitions/pbRegister'
    type: object
  pbGetUsersResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/pbRegister'
        type: array
    type: object
  pbLogin:
    properties:
      userEmail:
        type: string
      userPhone:
        type: string
    type: object
  pbMovie:
    properties:
      genre:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  pbRegister:
    properties:
      userAddress:
        type: string
      userDob:
        type: string
      userEmail:
        type: string
      userGender:
        type: string
      userId:
        type: string
      userName:
        type: string
      userPhone:
        type: string
      userPhoto:
        type: string
    type: object
  pbUpdateMovieRequest:
    properties:
      movie:
        $ref: '#/definitions/pbMovie'
    type: object
  pbUpdateMovieResponse:
    properties:
      movie:
        $ref: '#/definitions/pbMovie'
    type: object
  pbUpdateUserRequest:
    properties:
      UpdateUser:
        $ref: '#/definitions/pbRegister'
    type: object
  pbUpdateUserResponse:
    properties:
      UpdateUser:
        $ref: '#/definitions/pbRegister'
    type: object
  pbUploadImageRequest:
    properties:
      bucketName:
        type: string
      imageId:
        type: string
      imagePath:
        format: byte
        type: string
    type: object
  pbUploadImageResponse:
    properties:
      imageUrl:
        type: string
    type: object
  protobufAny:
    additionalProperties: {}
    properties:
      '@type':
        type: string
    type: object
  rpcStatus:
    properties:
      code:
        format: int32
        type: integer
      details:
        items:
          $ref: '#/definitions/protobufAny'
        type: array
      message:
        type: string
    type: object
info:
  title: image.proto
  version: version not set
paths:
  /v1/image/upload:
    post:
      operationId: ImageService_UploadImage
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pbUploadImageRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbUploadImageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - ImageService
  /v1/movie/create:
    post:
      operationId: MovieService_CreateMovie
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pbCreateMovieRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbCreateMovieResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - MovieService
  /v1/movie/delete:
    delete:
      operationId: MovieService_DeleteMovie
      parameters:
      - in: query
        name: id
        required: false
        type: string
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbDeleteMovieResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - MovieService
  /v1/movie/get:
    get:
      operationId: MovieService_GetMovie
      parameters:
      - in: query
        name: id
        required: false
        type: string
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbGetMovieResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - MovieService
  /v1/movie/gets:
    get:
      operationId: MovieService_GetMovies
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbGetMoviesResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - MovieService
  /v1/movie/update:
    put:
      operationId: MovieService_UpdateMovie
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pbUpdateMovieRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbUpdateMovieResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - MovieService
  /v1/user/create:
    post:
      operationId: UserService_RegisterUser
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pbCreateRegisterRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbCreateRegisterResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - UserService
  /v1/user/delete:
    delete:
      operationId: UserService_DeleteUserDetail
      parameters:
      - in: query
        name: userId
        required: false
        type: string
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbDeleteUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - UserService
  /v1/user/get:
    get:
      operationId: UserService_GetUser
      parameters:
      - in: query
        name: userRegister.userId
        required: false
        type: string
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbGetOneUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - UserService
  /v1/user/update:
    put:
      operationId: UserService_UpdateUserDetail
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pbUpdateUserRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbUpdateUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - UserService
  /v1/users/get:
    get:
      operationId: UserService_GetMultipleUsers
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbGetUsersResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - UserService
  /v1/users/login:
    post:
      operationId: UserService_LoginUser
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/pbCreateLoginRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbCreateLoginResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
      - UserService
produces:
- application/json
swagger: "2.0"
tags:
- name: ImageService
- name: MovieService
- name: UserService
